config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:new, :create, :index]
  end
  resources :categories, only: [:show]
  root controller: :articles, action: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :headline, presence: true
  validates :content, presence: true
  belongs_to :category
  belongs_to :user
  has_many :comments

  translates :headline, :content

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :articles
  translates :name
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_default_role, if: :new_record?

  enum role: [:subscriber, :journalist, :editor]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :role, presence: true
  has_many :articles
  has_many :comments

  private

    def set_default_role
      self.role ||= :subscriber
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :set_locale
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
  def user_not_authorized
    redirect_to root_path, notice: t('flash.pundit.not_authorized')
  end

  def set_locale
    I18n.locale = I18n.available_locales.include?(params[:locale]&.to_sym) ? params[:locale] : I18n.default_locale
    Rails.application.routes.default_url_options[:locale] = I18n.locale
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :load_categories, except: [:show]

  def index
    @articles = Article.where(published:true)
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.where(published:true)
    if @article.published== false && current_user != @article.user
      flash[:notice] = t('flash.article.in_process')
      redirect_to root_path
    end
  end

  def new
    @article = Article.new
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    @article.published = true if @article.user.editor?
    if @article.save
      flash_for_articles(@article.user)
      redirect_to root_path
    else
      flash[:alert] = @article.errors.full_messages.first
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
    authorize @article
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      @article.update(published: false) if current_user.journalist?
      flash_for_articles(current_user)
      redirect_to article_path(@article)
    else
      flash[:alert] = @article.errors.full_messages.first
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:notice] = t('flash.article.delete')
    else
      flash[:alert] = @article.errors.full_messages.first
    end
    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:headline, :content, :category_id)
  end

  def load_categories
    @categories = Category.all
  end

  def flash_for_articles(user)
    case user.role
    when 'journalist'
      flash[:notice] = t('flash.article.sent_approval')
    when 'editor'
      flash[:notice] = t('flash.article.published')
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @articles = Category.find(params[:id]).articles.where(published:true)
    render 'articles/index'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(content: comment_params[:content], article_id: article_params[:article_id], user: current_user)
    @comment.update(published:true) if current_user.editor?
    if @comment.save
      flash_for_comments(current_user)
    else
      flash[:alert] = @comment.errors.full_messages.first
    end
    redirect_to article_path(article_params[:article_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def article_params
    params.permit(:article_id)
  end

  def flash_for_comments(user)
    case user.role
    when 'editor'
      flash[:notice] = t('flash.comment.published')
    else
      flash[:notice] = t('flash.comment.sent_approval')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.haml
= form_with model: @article , local: true do |form|
  = form.label t('article.headline')
  %br
  = form.text_field :headline, placeholder: t('article.headline')
  %br
  = form.label t('article.content')
  %br
  = form.text_field :content, placeholder: t('article.content')
  %br
  = form.collection_select :category_id, @categories, :id, :name
  %br
  = form.submit t('article.form_submit')

app/views/articles/edit.html.haml
%h2= t('article.edit_page_title')

= render 'articles/form'

app/views/articles/index.html.haml
%h1= t('site_info.site_title')
#category-bar
  = link_to t('categories.all_categories'), root_path
  - @categories.each do |category|
    |
    = link_to category.name, category_path(category)
%hr

#article-list
  - @articles.each do |article|
    %h3= link_to article.headline, article_path(article)

app/views/articles/new.html.haml
%h2= t('article.new_page_title') 

= render 'articles/form'

app/views/articles/show.html.haml
%h3= @article.headline
%p= @article.content

%p= link_to t('article.edit_link'), edit_article_path(@article) if policy(@article).edit?
%p= link_to t('article.delete_link'), article_path(@article), method: :delete if policy(@article).destroy?

- @comments.each do |comment|
  %p= comment.content

= form_with scope: :comment, url: article_comments_path(@article), local: true do |form|
  = form.label t('comment.comment_content')
  = form.text_field :content, placeholder: t('comment.comment_content')
  = form.submit t('comment.submit')

= link_to t('article.back_link'), root_path

app/views/layouts/_navbar.html.haml
- if user_signed_in?
  = "Signed in as: #{current_user.role.capitalize} (#{current_user.email}) |"
  = link_to(t('navbar.create'), new_article_path) + " |" if policy(Article).new?
  = link_to t('navbar.sign_out'), destroy_user_session_path, method: :delete
- else
  = link_to t('navbar.sign_in'), new_user_session_path
  |
  = link_to t('navbar.sign_up'), new_user_registration_path

|
- if I18n.locale != I18n.default_locale
  = link_to t("navbar.language_en"), { locale: 'en' }
- else
  = link_to t("navbar.language_sv"), { locale: 'sv' }

app/views/layouts/application.html.haml
%html
  %head
    %title NewsroomApril
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    %p= notice
    %p= alert
    = yield